package com.ussr.pvz.view.gameplay;

import com.badlogic.gdx.scenes.scene2d.Group;
import com.badlogic.gdx.scenes.scene2d.Touchable;
import com.badlogic.gdx.scenes.scene2d.actions.Actions;
import com.ussr.pvz.model.App;
import com.ussr.pvz.model.engine.session.GameSession;
import com.ussr.pvz.model.entities.zombies.Zombie;
import com.ussr.pvz.view.animation.PamActor;
import pvz.libpvz.pam.PamPlayer;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Manages rendering of Ice Age Zomboss glacier block structures and fogging arrival effects.
 */
public class GlacierRenderLayer extends Group {

    private static final Pattern GLACIER_CLIP_PATTERN = Pattern.compile("glacier_column_(\\d+)");
    private static final int GLACIER_COLUMN_BASE = 7;

    private static final String GLACIER_BLOCK_PAM =
            "768/FULL/EFFECTS/ZOMBOSS_GLACIER_BLOCK/ZOMBOSS_GLACIER_BLOCK.PAM";
    private static final String GLACIER_BOTTOM_PAM =
            "768/FULL/EFFECTS/ZOMBOSS_GLACIER_BOTTOM/ZOMBOSS_GLACIER_BOTTOM.PAM";
    private static final String GLACIER_TOP_PAM =
            "768/FULL/EFFECTS/ZOMBOSS_GLACIER_TOP/ZOMBOSS_GLACIER_TOP.PAM";
    private static final String GLACIER_FOGGING_PAM =
            "768/FULL/EFFECTS/ZOMBOSS_GLACIER_FOGGING/ZOMBOSS_GLACIER_FOGGING.PAM";
    private static final String GLACIER_MIDDLE_PAM =
            "768/FULL/EFFECTS/ZOMBOSS_GLACIER_MIDDLE/ZOMBOSS_GLACIER_MIDDLE.PAM";

    private final PamPlayer pamPlayer;

    private final Map<String, CellGlacierNode> activeGlaciers = new HashMap<>();
    private final Set<Integer> zombossFrozenColumns = new HashSet<>();

    private boolean zombossArrived = false;

    private static class CellGlacierNode {
        PamActor actor;
        String pamPath;
        int state; // Used to track damage phases for the middle glacier (0=Full, 1=Damaged, 2=Broken)
    }

    public GlacierRenderLayer(PamPlayer pamPlayer) {
        this.pamPlayer = pamPlayer;
        setTouchable(Touchable.disabled);
    }

    @Override
    public void act(float delta) {
        super.act(delta);

        GameSession session = App.getGameSession();
        if (session == null) {
            clearGlaciers();
            return;
        }

        Zombie zomboss = findZomboss(session);

        // Ensure glaciers only generate and render for the Ice Age Mammoth Zomboss
        if (zomboss == null || !"ZombossMammoth".equals(zomboss.getAlias())) {
            clearGlaciers();
            return;
        }

        if (!zombossArrived) {
            zombossArrived = true;
            triggerArrivalFogging();
        }

        detectZombossColumnFreeze(zomboss);

        float hpRatio = getZombossHpRatio(zomboss);
        int zombossState = hpRatio > 0.66f ? 0 : (hpRatio > 0.33f ? 1 : 2);

        Set<String> currentKeys = new HashSet<>();

        // 1. Zomboss Glacier (Covers the last 3 columns, mapped centrally with one actor per row)
        int zombossCol = Math.max(0, LawnGridLayout.COLUMNS - 2); // Center of the 3 columns
        int startCol = Math.max(0, LawnGridLayout.COLUMNS - 3);

        for (int row = 0; row < LawnGridLayout.ROWS; row++) {
            String key = "zomboss_glacier_" + row;
            currentKeys.add(key);

            String pamPath;
            String clip;

            if (row == 0) {
                pamPath = GLACIER_BOTTOM_PAM;
                clip = "animation";
            } else if (row == LawnGridLayout.ROWS - 1) {
                pamPath = GLACIER_TOP_PAM;
                clip = "animation";
            } else {
                pamPath = GLACIER_MIDDLE_PAM;
                clip = zombossState == 0 ? "animation2" : (zombossState == 1 ? "animation" : "animation3");
            }

            // Do not loop the initial full-health state
            boolean loop = !clip.equals("animation2");

            syncGlacierNode(key, row, zombossCol, pamPath, clip, zombossState, loop);
        }

        // 2. Standard Block Columns (Frozen Columns generated by Zomboss)
        for (int col : zombossFrozenColumns) {
            if (col >= startCol) continue; // Do not overwrite the Zomboss's core glacier
            if (col < 0 || col >= LawnGridLayout.COLUMNS) continue;

            for (int row = 0; row < LawnGridLayout.ROWS; row++) {
                String key = row + "," + col;
                currentKeys.add(key);
                syncGlacierNode(key, row, col, GLACIER_BLOCK_PAM, "animation", -1, true);
            }
        }

        // Cleanup stale glacier nodes
        Iterator<Map.Entry<String, CellGlacierNode>> it = activeGlaciers.entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry<String, CellGlacierNode> entry = it.next();
            if (!currentKeys.contains(entry.getKey())) {
                entry.getValue().actor.remove();
                it.remove();
            }
        }

        // Y-Sort actors so those resting closer to the bottom (higher Y locally) render on top
        getChildren().sort((a, b) -> Float.compare(b.getY(), a.getY()));
    }

    private void syncGlacierNode(String key, int row, int col, String pamPath, String clip, int state, boolean loop) {
        CellGlacierNode node = activeGlaciers.get(key);
        float x = LawnGridLayout.centeredActorX(col, 80f);
        float y = LawnGridLayout.centeredActorY(row, 80f);

        if (node == null) {
            node = new CellGlacierNode();
            node.pamPath = pamPath;
            node.state = state;

            node.actor = new PamActor(pamPlayer, pamPath, clip);
            node.actor.setPamScale(0.85f);
            node.actor.setLooping(loop);
            node.actor.setTouchable(Touchable.disabled);
            node.actor.setPosition(x, y);

            addActor(node.actor);
            activeGlaciers.put(key, node);
        } else {
            node.actor.setPosition(x, y);

            // Rebuild the actor completely if the PAM path swaps
            if (!node.pamPath.equals(pamPath)) {
                node.actor.remove();
                node.pamPath = pamPath;
                node.state = state;

                node.actor = new PamActor(pamPlayer, pamPath, clip);
                node.actor.setPamScale(0.85f);
                node.actor.setLooping(loop);
                node.actor.setTouchable(Touchable.disabled);
                node.actor.setPosition(x, y);
                addActor(node.actor);

                // Update the animation clip dynamically if just changing damage phases
            } else if (node.state != state) {
                node.state = state;
                node.actor.setClip(clip);
                node.actor.setLooping(loop);
            }
        }
    }

    private Zombie findZomboss(GameSession session) {
        if (session == null || session.getZombies() == null) return null;
        for (Zombie zombie : session.getZombies()) {
            if (zombie.getZombossController() != null
                    || (zombie.getAlias() != null && zombie.getAlias().toLowerCase().contains("zomboss"))) {
                return zombie;
            }
        }
        return null;
    }

    private void triggerArrivalFogging() {
        PamActor foggingActor = new PamActor(pamPlayer, GLACIER_FOGGING_PAM, "animation");
        foggingActor.setPamScale(1.2f);
        foggingActor.setLooping(false);
        foggingActor.setTouchable(Touchable.disabled);

        float x = LawnGridLayout.cellX(LawnGridLayout.COLUMNS - 2) + LawnGridLayout.CELL_WIDTH / 2f;
        float y = LawnGridLayout.cellY(LawnGridLayout.ROWS / 2) + LawnGridLayout.CELL_HEIGHT / 2f;
        foggingActor.setPosition(x, y);

        addActor(foggingActor);

        foggingActor.addAction(Actions.sequence(
                Actions.delay(3.0f),
                Actions.removeActor()
        ));
    }
    private void detectZombossColumnFreeze(Zombie zomboss) {
        if (zomboss == null || zomboss.getZombossController() == null) return;

        List<String> clips = zomboss.getZombossController().getLastMoveClips();
        if (clips == null) return;

        for (String clip : clips) {
            if (clip == null) continue;
            Matcher m = GLACIER_CLIP_PATTERN.matcher(clip);
            if (m.find()) {
                try {
                    int x = Integer.parseInt(m.group(1));
                    int colIndex = GLACIER_COLUMN_BASE - x;
                    if (colIndex >= 0 && colIndex < LawnGridLayout.COLUMNS) {
                        zombossFrozenColumns.add(colIndex);
                    }
                } catch (NumberFormatException ignored) {
                }
            }
        }
    }
    private float getZombossHpRatio(Zombie zomboss) {
        if (zomboss == null) return 1f;
        try {
            java.lang.reflect.Method getHp = zomboss.getClass().getMethod("getHitpoints");
            java.lang.reflect.Method getMaxHp = zomboss.getClass().getMethod("getMaxHitpoints");
            float hp = ((Number) getHp.invoke(zomboss)).floatValue();
            float max = ((Number) getMaxHp.invoke(zomboss)).floatValue();
            return max > 0f ? hp / max : 1f;
        } catch (Exception e1) {
            try {
                java.lang.reflect.Method getHp = zomboss.getClass().getMethod("getHp");
                java.lang.reflect.Method getMaxHp = zomboss.getClass().getMethod("getMaxHp");
                float hp = ((Number) getHp.invoke(zomboss)).floatValue();
                float max = ((Number) getMaxHp.invoke(zomboss)).floatValue();
                return max > 0f ? hp / max : 1f;
            } catch (Exception e2) {
                return 1f; // Failsafe state
            }
        }
    }

    private void clearGlaciers() {
        for (CellGlacierNode node : activeGlaciers.values()) {
            if (node.actor != null) node.actor.remove();
        }
        activeGlaciers.clear();
        zombossFrozenColumns.clear();
        zombossArrived = false;
    }
}