package com.ussr.pvz.view.gameplay;

import com.badlogic.gdx.scenes.scene2d.Group;
import com.badlogic.gdx.scenes.scene2d.Touchable;
import com.badlogic.gdx.scenes.scene2d.actions.Actions;
import com.ussr.pvz.model.App;
import com.ussr.pvz.model.board.Cell;
import com.ussr.pvz.model.board.structures.GlacierBlock;
import com.ussr.pvz.model.board.structures.ZombossMidGlacier;
import com.ussr.pvz.model.engine.session.GameSession;
import com.ussr.pvz.model.entities.zombies.Zombie;
import com.ussr.pvz.view.animation.PamActor;
import pvz.libpvz.pam.PamPlayer;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;

/**
 * Manages rendering of Ice Age Zomboss glacier block structures and fogging arrival effects.
 */
public class GlacierRenderLayer extends Group {

    private static final String GLACIER_BLOCK_PAM =
            "768/FULL/EFFECTS/ZOMBOSS_GLACIER_BLOCK/ZOMBOSS_GLACIER_BLOCK.PAM";
    private static final String GLACIER_BOTTOM_PAM =
            "768/FULL/EFFECTS/ZOMBOSS_GLACIER_BOTTOM/ZOMBOSS_GLACIER_BOTTOM.PAM";
    private static final String GLACIER_TOP_PAM =
            "768/FULL/EFFECTS/ZOMBOSS_GLACIER_TOP/ZOMBOSS_GLACIER_TOP.PAM";
    private static final String GLACIER_FOGGING_PAM =
            "768/FULL/EFFECTS/ZOMBOSS_GLACIER_FOGGING/ZOMBOSS_GLACIER_FOGGING.PAM";
    private static final String GLACIER_MIDDLE_PAM =
            "768/FULL/EFFECTS/ZOMBOSS_GLACIER_MIDDLE/ZOMBOSS_GLACIER_MIDDLE.PAM";

    private final PamPlayer pamPlayer;

    private final Map<String, CellGlacierNode> activeGlaciers = new HashMap<>();

    /**
     * Cells (row,col) that currently have a *living* GlacierBlock from a
     * ColumnFreeze sweep. Tracked per-cell (not per-column) so that a single
     * block dying stops rendering just that block instead of the whole
     * column waiting for every block in it to die.
     */
    private final Set<String> zombossFrozenCells = new HashSet<>();

    private boolean zombossArrived = false;

    private static class CellGlacierNode {
        PamActor actor;
        String pamPath;
        int state; // Used to track damage phases for the middle glacier (0=Full, 1=Damaged, 2=Broken)
    }

    public GlacierRenderLayer(PamPlayer pamPlayer) {
        this.pamPlayer = pamPlayer;
        setTouchable(Touchable.disabled);
    }

    @Override
    public void act(float delta) {
        super.act(delta);

        GameSession session = App.getGameSession();
        if (session == null) {
            clearGlaciers();
            return;
        }

        Zombie zomboss = findZomboss(session);

        // Ensure glaciers only generate and render for the Ice Age Mammoth Zomboss
        if (zomboss == null || !"ZombossMammoth".equals(zomboss.getAlias())) {
            clearGlaciers();
            return;
        }

        if (!zombossArrived) {
            zombossArrived = true;
            triggerArrivalFogging();
        }

        detectZombossFrozenCells(session);

        // State now comes from the actual hittable ZombossMidGlacier armor
        // (see ZombossController) instead of the boss's raw HP ratio, so it
        // reacts to real hits and reverts on stun recovery.
        ZombossMidGlacier midGlacier = zomboss.getZombossController() != null
                ? zomboss.getZombossController().getMidGlacier()
                : null;

        int zombossState;
        if (midGlacier == null) {
            zombossState = 0;
        } else {
            zombossState = switch (midGlacier.getState()) {
                case FULL -> 0;
                case DAMAGED -> 1;
                case DESTROYED -> 2;
            };
        }

        Set<String> currentKeys = new HashSet<>();

        // 1. Zomboss Glacier (Covers the last 3 columns, mapped centrally with one actor per row)
        int zombossCol = Math.max(0, LawnGridLayout.COLUMNS - 2); // Center of the 3 columns
        int startCol = Math.max(0, LawnGridLayout.COLUMNS - 3);

        for (int row = 0; row < LawnGridLayout.ROWS; row++) {
            String key = "zomboss_glacier_" + row;
            currentKeys.add(key);

            String pamPath;
            String clip;

            if (row == 0) {
                pamPath = GLACIER_BOTTOM_PAM;
                clip = "animation";
            } else if (row == LawnGridLayout.ROWS - 1) {
                pamPath = GLACIER_TOP_PAM;
                clip = "animation";
            } else {
                pamPath = GLACIER_MIDDLE_PAM;
                clip = zombossState == 0 ? "animation2" : (zombossState == 1 ? "animation" : "animation3");
            }

            // Only the "damaged" clip loops; the default and destroyed clips both play once.
            boolean loop = clip.equals("animation");

            syncGlacierNode(key, row, zombossCol, pamPath, clip, zombossState, loop);
        }

        // 2. Standard Block Cells (individual frozen cells generated by ColumnFreeze)
        for (String cellKey : zombossFrozenCells) {
            String[] parts = cellKey.split(",");
            int row = Integer.parseInt(parts[0]);
            int col = Integer.parseInt(parts[1]);

            if (col >= startCol) continue; // Do not overwrite the Zomboss's core glacier
            if (col < 0 || col >= LawnGridLayout.COLUMNS) continue;

            currentKeys.add(cellKey);
            syncGlacierNode(cellKey, row, col, GLACIER_BLOCK_PAM, "animation", -1, true);
        }

        // Cleanup stale glacier nodes (this is what stops rendering a block
        // the instant it's destroyed — it simply drops out of currentKeys)
        Iterator<Map.Entry<String, CellGlacierNode>> it = activeGlaciers.entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry<String, CellGlacierNode> entry = it.next();
            if (!currentKeys.contains(entry.getKey())) {
                entry.getValue().actor.remove();
                it.remove();
            }
        }

        // Y-Sort actors so those resting closer to the bottom (higher Y locally) render on top
        getChildren().sort((a, b) -> Float.compare(b.getY(), a.getY()));
    }

    private void syncGlacierNode(String key, int row, int col, String pamPath, String clip, int state, boolean loop) {
        CellGlacierNode node = activeGlaciers.get(key);
        float x = LawnGridLayout.centeredActorX(col, 80f);
        float y = LawnGridLayout.centeredActorY(row, 80f);

        if (node == null) {
            node = new CellGlacierNode();
            node.pamPath = pamPath;
            node.state = state;

            node.actor = new PamActor(pamPlayer, pamPath, clip);
            node.actor.setPamScale(0.85f);
            node.actor.setLooping(loop);
            node.actor.setTouchable(Touchable.disabled);
            node.actor.setPosition(x, y);

            addActor(node.actor);
            activeGlaciers.put(key, node);
        } else {
            node.actor.setPosition(x, y);

            // Rebuild the actor completely if the PAM path swaps
            if (!node.pamPath.equals(pamPath)) {
                node.actor.remove();
                node.pamPath = pamPath;
                node.state = state;

                node.actor = new PamActor(pamPlayer, pamPath, clip);
                node.actor.setPamScale(0.85f);
                node.actor.setLooping(loop);
                node.actor.setTouchable(Touchable.disabled);
                node.actor.setPosition(x, y);
                addActor(node.actor);

                // Update the animation clip dynamically if just changing damage phases
            } else if (node.state != state) {
                node.state = state;
                node.actor.setClip(clip);
                node.actor.setLooping(loop);
            }
        }
    }

    private Zombie findZomboss(GameSession session) {
        if (session == null || session.getZombies() == null) return null;
        for (Zombie zombie : session.getZombies()) {
            if (zombie.getZombossController() != null
                    || (zombie.getAlias() != null && zombie.getAlias().toLowerCase().contains("zomboss"))) {
                return zombie;
            }
        }
        return null;
    }

    private void triggerArrivalFogging() {
        PamActor foggingActor = new PamActor(pamPlayer, GLACIER_FOGGING_PAM, "animation");
        foggingActor.setPamScale(1.2f);
        foggingActor.setLooping(false);
        foggingActor.setTouchable(Touchable.disabled);

        float x = LawnGridLayout.cellX(LawnGridLayout.COLUMNS - 2) + LawnGridLayout.CELL_WIDTH / 2f;
        float y = LawnGridLayout.cellY(LawnGridLayout.ROWS / 2) + LawnGridLayout.CELL_HEIGHT / 2f;
        foggingActor.setPosition(x, y);

        addActor(foggingActor);

        foggingActor.addAction(Actions.sequence(
                Actions.delay(3.0f),
                Actions.removeActor()
        ));
    }

    /**
     * Scans the lawn directly (instead of relying on the tickable sweep's
     * own bookkeeping) and records exactly which cells currently hold a
     * living GlacierBlock. This way, once a specific block's takeDamage()
     * kills it (cell.getInteractableStructure().isAlive() == false, or the
     * structure was cleared from the cell entirely), that single cell's key
     * disappears from this set on the very next frame and its PAM actor is
     * removed — independent of the rest of the column.
     */
    private void detectZombossFrozenCells(GameSession session) {
        if (session == null || session.getLawn() == null) return;

        zombossFrozenCells.clear();
        for (int row = 0; row < session.getLawn().getRows(); row++) {
            for (int col = 0; col < session.getLawn().getCols(); col++) {
                Cell cell = session.getLawn().getCell(row, col);
                if (cell == null) continue;

                var structure = cell.getInteractableStructure();
                if (!(structure instanceof GlacierBlock) || !structure.isAlive()) continue;

                zombossFrozenCells.add(row + "," + col);
            }
        }
    }

    private void clearGlaciers() {
        for (CellGlacierNode node : activeGlaciers.values()) {
            if (node.actor != null) node.actor.remove();
        }
        activeGlaciers.clear();
        zombossFrozenCells.clear();
        zombossArrived = false;
    }
}