package com.ussr.pvz.shared.network;

public enum RequestType {
    PING,

    LOGIN,
    REGISTER,
    COMPLETE_REGISTRATION,

    FORGOT_PASSWORD,
    ANSWER_SECURITY_QUESTION,
    RESET_PASSWORD,

    AUTH_TOKEN,
    LOGOUT,

    GET_PROFILE,
    CHANGE_USERNAME,
    CHANGE_NICKNAME,
    CHANGE_EMAIL,
    CHANGE_PASSWORD,

    GET_LEADERBOARD,

    FIND_RANDOM_MATCH,
    CANCEL_RANDOM_MATCH,

    CHALLENGE_PLAYER,
    ACCEPT_CHALLENGE,
    REJECT_CHALLENGE,

    GAME_ACTION,
    GAME_STATE,

    SEND_REACTION
}